app_noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    path('', views.index, name='index'),
    path('noticias/', views.noticias, name='noticias'),
    path('noticias/<int:id>', views.noticia, name='noticia'),
    path('autores/', views.autores, name='autores'),
    path('autores/<int:id>', views.autor, name='autor'),
]

proj_blog_noticias/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app_noticias.urls", namespace="noticias")),
    path('users/', include("users.urls", namespace="users")), 
]

users/urls.py
"""Define padrões de URL para users"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

app_noticias/models.py
from django.db import models
from django.contrib.auth.models import User


class Noticia(models.Model):
    titulo = models.CharField(max_length=100)
    sub_titulo = models.CharField(max_length=150)
    data = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField()

    def __str__(self):
        return self.titulo
    

class Comentario(models.Model):
    texto = models.TextField()
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if len(self.texto) > 50:
            return self.texto[:50] + "..."
        else:
            return self.texto

users/models.py
from django.db import models

# Create your models here.

app_noticias/views.py
from django.shortcuts import render
from django.core.paginator import Paginator

from .models import Noticia, Comentario
from django.contrib.auth.models import User

def index(request):
    template = 'noticias/index.html'
    return render(request, template)


def noticias(request):
    template = 'noticias/noticias.html'
    noticias = Noticia.objects.all().order_by('-data')
   
    paginator = Paginator(noticias, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'noticias': page_obj
        }
    return render(request, template , context)

def noticia(request, id):
    template = 'noticias/noticia.html'
    noticia = Noticia.objects.get(id=id)
    comentarios = Comentario.objects.filter(noticia=id).order_by('-data')

    context = {
        'noticia': noticia,
        'comentarios': comentarios 
        }
    return render(request, template , context)


def autores(request):
    template = 'noticias/autores.html'
    autores = User.objects.all().filter().order_by('username')

    paginator = Paginator(autores, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'autores': page_obj
        }
    return render(request, template , context)


def autor(request, id):
    template = 'noticias/autor.html'
    autor = User.objects.get(id=id)
    noticias = Noticia.objects.filter(autor=id).order_by('-data')

    context = {
        'autor': autor,
        'noticias': noticias 
        }
    return render(request, template , context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

from django import forms
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(label='Nome', max_length=30)
    last_name = forms.CharField(label='Sobrenome', max_length=30)    
    email = forms.EmailField(label='Email', required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email')
 

def logout_view(request):
    """Faz o Log out do usuário"""
    logout(request)
    return HttpResponseRedirect(reverse('noticias:index'))


def register(request):
    """Faz o cadastro de um novo usuário"""
    if request.method != 'POST':
        # Exibe o formulário de cadastro em branco
        form = CustomUserCreationForm()
    else:
        # Processa o formulário preenchido
        form = CustomUserCreationForm(data=request.POST)

        if form.is_valid():
            novo_usuario = form.save()
            # Faz o login do usuário e o redireciona para a página inicial
            autentificacao = authenticate(username=novo_usuario.username, password=request.POST['password1'])
            login(request, autentificacao)
            return HttpResponseRedirect(reverse('noticias:index'))
        
    template = 'users/register.html'
    context = {
        'form': form
    }
    return render(request, template, context)

app_noticias/templates/noticias/autor.html
{% extends "noticias/base.html" %}

{% block content %}

    <div class="card">
        <div class="card-header">
            <div class="row">
                <h4 class="text-primary">{{ autor.username}}</h4>
            </div>           
        </div>
        <div class="card-body">            
                Nome Completo: {{ autor.first_name}} {{ autor.last_name}}
                <br>
                E-mail: {{ autor.email}}                      
        </div>            
    </div>
    <br>
    <h4 style="text-align: center;"> Noticias Publicadas </h4>
    {% for noticia in noticias %}
        <div class="card">
            <div class="card-header">
                <div class='row'>
                    <h4><a href="{% url 'noticias:noticia' noticia.id %}" style="text-decoration: none;">{{ noticia.titulo }}</a></h4>
                    <div class="row">
                        <h6> {{ noticia.data|date:'d / M / Y - H:i' }} </h6>
                    </div> 
                </div>
            </div>           
  
            <div class="card-body">
                <span>{{ noticia.sub_titulo }}</span>
            </div>      
        </div>
        <br>
    {% empty %}
        <h5>Ainda não há noticias registradas deste Autor.</h5>
    {% endfor %}

     
{% endblock %}

app_noticias/templates/noticias/autores.html
{% extends "noticias/base.html" %}

{% block content %}

    {% for autor in autores %}
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="row">
                        <h4><a href="{% url 'noticias:autor' autor.id %}" style="text-decoration: none;">{{ autor.username }}</a></h4>
                    </div>
                    <div class="row" >
                        <div class="col"><h6>{{ autor.first_name}} {{ autor.last_name}}</h6></div>
                    </div> 
                </div>           
            </div>
        </div>
        <br>
    {% empty %}
        <h4>Ainda não há nóticias cadastradas.</h4>
    {% endfor %}

    <nav class="d-flex justify-content-center" aria-label="Page navigation example">
        <ul class="pagination">
          <li class="page-item">
            {% if autores.has_previous %}
              <a href="?page={{autores.previous_page_number}}" class="page-link">
                  <span aria-hidden="true">&laquo;</span>
              </a>
            {% endif %}
          </li>
          <li class="page-item"><a class="page-link" href="#">{{ autores.number }}</a></li>
          <li class="page-item">
            {% if autores.has_next %}
              <a href="?page={{autores.next_page_number}}" class="page-link">
                  <span aria-hidden="true">&raquo;</span>
              </a>
            {% endif %}
          </li>
        </ul>
    </nav>
     
{% endblock %}

app_noticias/templates/noticias/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <!-- Bootstrap CSS -->
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  
  <title>Blog de Notícias</title>
  
</head>

<body>
  <div class="container-fluid">
    {% include 'noticias/navbar.html' %}
    <div class="container">
      <div class="my-4">   
        <h3 class="display-6">
          {% block header %}
          {% endblock %}
        </h3>
      </div>
    </div>
      
    <div class="container">
      <div class="my-1">    
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

app_noticias/templates/noticias/index.html
{% extends "noticias/base.html" %}

{% block header %}
    <div class="container" style="text-align: center ;">
        <h1><hr></h1>
        <h1>Bem-vindo(a) ao Ponto de Vista: Notícias em Destaque.</h1>
        <h1><hr></h1>
        <h3>O seu destino confiável para notícias atualizadas e informações relevantes. </h3>
    </div>   
{% endblock %}

{% block content %}
    <div class="container" style="text-align: justify;">        
        <h4>Blog Ponto de Vista, o seu portal de notícias dedicado a trazer informações precisas e oportunas 
            sobre os assuntos que mais importam. Aqui você encontrará uma ampla gama de tópicos, desde notícias locais e internacionais 
            até esportes, entretenimento, saúde, tecnologia e muito mais. Nossa missão é mantê-lo(a) informado(a) sobre os eventos mais 
            recentes e fornecer uma perspectiva única sobre os assuntos em destaque.</h4>
        <h4>Em Blog Ponto de Vista, acreditamos no poder da informação. Nossa equipe de jornalistas experientes e comprometidos busca 
            constantemente as histórias mais relevantes e traz para você uma cobertura completa e imparcial. Queremos que você tenha 
            acesso a notícias confiáveis e análises aprofundadas, para que possa formar suas próprias opiniões e tomar decisões bem 
            fundamentadas.</h4>
        <h4>Navegue pelo nosso site e descubra uma variedade de artigos interessantes, reportagens exclusivas, entrevistas cativantes e 
            colunas de especialistas. Além disso, você pode aproveitar recursos multimídia, como vídeos e galerias de fotos, para uma 
            experiência de leitura mais envolvente.</h4>
        <h4>No "Ponto de Vista: Notícias em Destaque", acreditamos na importância da comunidade. Queremos ouvir a sua voz e encorajamos a participação dos leitores. 
            Fique à vontade para compartilhar suas opiniões e comentários nas seções de comentários de nossos artigos, ou entre em contato 
            conosco diretamente. Valorizamos a sua perspectiva e nos esforçamos para criar um espaço inclusivo e respeitoso para todos.</h4>
        <h4>Estamos comprometidos em fornecer notícias e informações de qualidade, com precisão e integridade jornalística. Acompanhe-nos 
            diariamente para se manter atualizado(a) sobre o que está acontecendo ao redor do mundo e em sua comunidade. Assine nossa 
            newsletter para receber as últimas notícias diretamente em sua caixa de entrada e siga-nos em nossas redes sociais para se 
            conectar conosco e não perder nenhuma atualização.</h4>
        <h4>Obrigado(a) por nos escolher como sua fonte confiável de notícias. Estamos entusiasmados em compartilhar essa jornada informativa
             com você. Prepare-se para explorar um mundo de conhecimento, inspiração e descobertas no "Ponto de Vista: Notícias em Destaque"!</h4>
        <br>
        <h4>Equipe do Blog - Ponto de Vista".</h4>
    </div> 
{% endblock %}

app_noticias/templates/noticias/navbar.html
<nav class="navbar navbar-expand-md navbar-light" style="background-color: #aaacad;">
  <div class="container-fluid container">
      
    <a class="navbar-brand" href="{% url 'noticias:index' %}">Blog - Ponto de Vista</a>
    <button class="navbar-toggler" 
      type="button" 
      data-bs-toggle="collapse" 
      data-bs-target="#navbarSupportedContent" 
      aria-controls="navbarSupportedContent" 
      aria-expanded="false" 
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>    

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item"><a class="nav-link" href="{% url 'noticias:noticias' %}">Noticias</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'noticias:autores' %}">Autores</a></li>
        </ul>
      {% if user.is_authenticated %}
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <span class="navbar-text"> Olá, {{ user.username }} </span>
          <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Log out</a></li>
        </ul>
      {% else %}
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <span class="nav-link dropdown-toggle" 
              id="navbarDropdown" 
              role="button" 
              data-bs-toggle="dropdown" 
              aria-expanded="false">
            Entradas de Usuário
            </span>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li class="dropdown-item"><a class="nav-link" href="{%  url 'users:register' %}">Registrar</a></li>
              <li class="dropdown-item"><a class="nav-link" href="{%  url 'users:login' %}">Log in</a></li>
            </ul>
          </li>
        </ul>
      {% endif %}
    </div>
  </div>
</nav>

app_noticias/templates/noticias/noticia.html
{% extends "noticias/base.html" %}

{% block content %}

    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="row">
                    <h4 class="text-primary">{{ noticia.titulo}}</h4>
                </div>
                <div class="row" >
                    <h6>
                        Autor: <span class="badge bg-warning"><a href="#" style="text-decoration: none;">{{ noticia.autor}}</a></span>
                        <br>
                        Publicado em: {{ noticia.data|date:'d / M / Y - H:i' }}
                    </h6>
                </div> 
            </div>           
        </div>
        <div class="card-body" style="text-align: justify;">            
                {{ noticia.texto|linebreaks }}                      
        </div>            
    </div>
    <br>
    <h4 style="text-align: center;"> Comentários </h4>
    {% for comentario in comentarios %}
        <div class="card">
            <div class="card-header">
                <div class='row'>
                    <div class="col" >
                        <h6> {{ comentario.autor}}</h6>
                    </div>  
                    <div class="col" style="text-align: right;">
                        <h6> {{ comentario.data|date:'d / M / Y - H:i' }} </h6>
                    </div> 
                </div>
            </div>           
  
            <div class="card-body" style="text-align: justify;">
                <span>{{ comentario.texto|linebreaks}}</span>
            </div>      
        </div>
        <br>
    {% empty %}
        <h5>Ainda não há comentários cadastrados.</h5>
    {% endfor %}

     
{% endblock %}

app_noticias/templates/noticias/noticias.html
{% extends "noticias/base.html" %}

{% block content %}

    {% for noticia in noticias %}
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="row">
                        <h4><a href="{% url 'noticias:noticia' noticia.id %}" style="text-decoration: none;">{{ noticia.titulo }}</a></h4>
                    </div>
                    <div class="row" >
                        <div class="col"><h6>Autor: <span class="badge bg-warning"><a href="#" style="text-decoration: none;">{{ noticia.autor }}</a></span></h6></div>
                        <div class="col" style="text-align: right;">
                            <h6>Publicado em: {{ noticia.data|date:'d / M / Y - H:i' }}</h6>
                        </div>
                    </div> 
                </div>           
            </div>  
            <div class="card-body" style="text-align: justify;">
                <span> {{ noticia.sub_titulo}} </span>
            </div>      
        </div>
        <br>
    {% empty %}
        <h4>Ainda não há nóticias cadastradas.</h4>
    {% endfor %}

    <nav class="d-flex justify-content-center" aria-label="Page navigation example">
        <ul class="pagination">
          <li class="page-item">
            {% if noticias.has_previous %}
              <a href="?page={{noticias.previous_page_number}}" class="page-link">
                  <span aria-hidden="true">&laquo;</span>
              </a>
            {% endif %}
          </li>
          <li class="page-item"><a class="page-link" href="#">{{ noticias.number }}</a></li>
          <li class="page-item">
            {% if noticias.has_next %}
              <a href="?page={{noticias.next_page_number}}" class="page-link">
                  <span aria-hidden="true">&raquo;</span>
              </a>
            {% endif %}
          </li>
        </ul>
    </nav>
     
{% endblock %}

users/templates/users/login.html
{% extends "noticias/base.html" %}
{% load django_bootstrap5 %}

{% block header%}
    Entre em sua conta
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        
            <button name="submit" class="btn btn-primary">log in</button>

        <input type="hidden" name="next" value="{% url 'noticias:index' %}" />
    </form>

{% endblock %}

users/templates/users/register.html
{% extends "noticias/base.html" %}
{% load django_bootstrap5 %}

{% block header%}
    Registro de novo usuário
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'users:register' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

            <button name="submit" class="btn btn-primary">Registar</button>

        <input type="hidden" name="next" value="{% url 'noticias:index' %}" />
    </form>

{% endblock %}